### PR TITLE
Extend to 9 additional model architectures

### PR DESCRIPTION
**Pull request by cregouby**
I've extend golgotha to cover 9 more model architectures.

This implies function name generalization to `transformer_model_download()` and `transformer()`
`BERT_model_download()` and `BERT()` have been kept in the code-base for compatibility, but are not mentionned anymore in the Readme.

For me `distilBERT` was a must for its lower footprint and higher inference performance.
Having gone through RBERT and tf.hub to get it, your project is amazingly easier to expand !

### CODE REVIEW

**Comment by jwijffels** [comment]
thanks! looks great. just a few questions

- could you remove the usage of assertthat and replace it with e.g. stopifnot
- are we also sure that the logic of these extra models is the same regarding extraction of the embedding?
- does all of this increase the dependency of the transformer library to a newer version?

**Comment by cregouby** [comment]
I will turn assertthat into stopifnot, for sure ( I was too lazy first).
The logic for other model works like a charm (tested for `architecture="DistilBERT"` and `architecture="XLM-RoBERTa"` familly, the latest having a different vocab and tokenizer).
My running version of transformers is 2.5.1 (for an unknown reason). I'll try to downgrade as there is no specific requirement to change from 2.4.1. If any, I will update DESCRIPTION accordingly.
I'll let you know.

**Comment by cregouby** [comment]
Code runs fine with current transformer version 2.4.1

**Comment by jwijffels** [comment]
please check on all code in the examples and make sure all are running fine - even the ones in a dontrun block
e.g. you have nlp$Bertdownload but Bertdownload is no longer defined.
Also, do not include architectures which you haven't checked. I see you list up "GTP", "GTP-2", "CTRL", "Transformer-XL", "XLNet", "XLM", "DistilBERT", "RoBERTa", "XLM-RoBERTa". Only include the ones which are working. No need to have code in here which is not used.
please also do not duplicate code, if your predict.transformer is the same as predict.BERT use predict.BERT in predict.transformer to avoid duplicated code
why also not keep the architecture in the python object?

**Comment by jwijffels** [comment]
Thanks although the unit tests are failing, I'll incorporate it an work from there. FYI. I'm getting this on Windows regarding unit tests.

```
> test_check("golgotha")
Downloading: 100%|##########| 872k/872k [00:00<00:00, 907kB/s]  RLIBS_2b8050d03f17/golgotha/models/bert-base-multilingual-uncased
Downloading: 100%|##########| 569/569 [00:00<00:00, 36.5kB/s]
Downloading: 100%|##########| 672M/672M [11:47<00:00, 950kB/s]-- 1. Failure: transformer_download_model() with default create all required mod
file.exists(paste0(model_path, "config.json")) isn't true.

-- 2. Failure: transformer_download_model() with default create all required mod
file.exists(paste0(model_path, "pytorch_model.bin")) isn't true.

-- 3. Failure: transformer_download_model() with default create all required mod
file.exists(paste0(model_path, "special_tokens_map.json")) isn't true.

-- 4. Failure: transformer_download_model() with default create all required mod
file.exists(paste0(model_path, "tokenizer_config.json")) isn't true.

-- 5. Failure: transformer_download_model() with default create all required mod
file.exists(paste0(model_path, "vocab.txt")) isn't true.

Downloading model to C:/Users/Jan/AppData/Local/Temp/RtmpyeaUwg/RLIBS_2b8050d03f17/golgotha/models/bert-base-multilingual-uncased-- 6. Failure: second occurence of the same transformer_download_model() uses ca
<... isn't true.

Downloading model to ~/.cache/RBERT/openai-gpt
Downloading: 100%|##########| 816k/816k [00:01<00:00, 496kB/s]  
Downloading: 100%|##########| 458k/458k [00:00<00:00, 551kB/s]  
ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.
Downloading: 100%|##########| 326/326 [00:00<?, ?B/s] 
Downloading: 100%|##########| 479M/479M [09:45<00:00, 818kB/s]Downloading model to ~/.cache/RBERT/gpt2
Downloading: 100%|##########| 1.04M/1.04M [00:01<00:00, 832kB/s] 
Downloading: 100%|##########| 456k/456k [00:02<00:00, 166kB/s]  
Downloading: 100%|##########| 224/224 [00:00<00:00, 44.8kB/s]
Downloading: 100%|##########| 548M/548M [11:22<00:00, 804kB/s]Downloading model to ~/.cache/RBERT/transfo-xl-wt103
Downloading: 100%|##########| 9.14M/9.14M [00:09<00:00, 932kB/s] 
Downloading: 100%|##########| 659/659 [00:00<?, ?B/s] 
Downloading: 100%|##########| 1.14G/1.14G [18:55<00:00, 1.01MB/s]Downloading model to ~/.cache/RBERT/xlnet-base-cased
Downloading: 100%|##########| 798k/798k [00:00<00:00, 863kB/s] 
Downloading: 100%|##########| 690/690 [00:00<00:00, 98.5kB/s]
Downloading: 100%|##########| 467M/467M [07:43<00:00, 1.01MB/s]Downloading model to ~/.cache/RBERT/xlm-mlm-enfr-1024
Downloading: 100%|##########| 1.45M/1.45M [00:01<00:00, 728kB/s]
Downloading: 100%|##########| 1.01M/1.01M [00:01<00:00, 763kB/s]
Downloading: 100%|##########| 447/447 [00:00<00:00, 74.5kB/s]
Downloading: 100%|##########| 830M/830M [13:23<00:00, 1.03MB/s]Downloading model to ~/.cache/RBERT/distilbert-base-cased-- 7. Error: DistilBERT model architecture can be download (@test-embed.R#32)  -
OSModel name 'distilbert-base-cased' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased). We assumed 'distilbert-base-cased' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

Detailed traceback: 
  File "<string>", line 47, in download
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\tokenization_utils.py", line 309, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\tokenization_utils.py", line 410, in _from_pretrained
    list(cls.vocab_files_names.values()),
Backtrace:
 1. golgotha::transformer_download_model(...)
 2. nlp$download(...)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

Downloading model to ~/.cache/RBERT/roberta-base
Downloading: 100%|##########| 899k/899k [00:01<00:00, 778kB/s] 
Downloading: 100%|##########| 456k/456k [00:00<00:00, 761kB/s] 
Downloading: 100%|##########| 524/524 [00:00<?, ?B/s] 
Downloading: 100%|##########| 501M/501M [08:46<00:00, 951kB/s]Downloading model to ~/.cache/RBERT/xlm-roberta-base
Downloading: 100%|##########| 5.07M/5.07M [00:05<00:00, 944kB/s] 
Downloading: 100%|##########| 737/737 [00:00<00:00, 174kB/s]
Downloading: 100%|##########| 1.12G/1.12G [18:45<00:00, 991kB/s] Downloading model to C:/Users/Jan/AppData/Local/Temp/RtmpyeaUwg/RLIBS_2b8050d03f17/golgotha/models/non-existing-model-name-- 8. Error: GTP model architecture can be loaded and is able to tokenize senten
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTopenai-gpt' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTopenai-gpt/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 9. Error: GTP-2 model architecture can be loaded and is able to tokenize sent
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTgpt2' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTgpt2/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 10. Error: Transformer-XL model architecture can be loaded and is able to tok
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTtransfo-xl-wt103' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTtransfo-xl-wt103/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 11. Error: XLNet model architecture can be loaded and is able to tokenize sen
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTxlnet-base-cased' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTxlnet-base-cased/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 12. Error: XLM model architecture can be loaded and is able to tokenize sente
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTxlm-mlm-enfr-1024' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTxlm-mlm-enfr-1024/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 13. Error: DistilBERT model architecture can be loaded and is able to tokeniz
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTdistilbert-base-cased' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTdistilbert-base-cased/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 14. Error: RoBERTa model architecture can be loaded and is able to tokenize s
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTroberta-base' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTroberta-base/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

-- 15. Error: XLM-RoBERTa model architecture can be loaded and is able to tokeni
OSModel name 'C:/Users/Jan/Documents/.cache/RBERTxlm-roberta-base' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/C:/Users/Jan/Documents/.cache/RBERTxlm-roberta-base/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Detailed traceback: 
  File "<string>", line 22, in __init__
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\modeling_utils.py", line 389, in from_pretrained
    **kwargs,
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Anaconda3\envs\r-reticulate\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
Backtrace:
 1. golgotha::transformer(...)
 2. nlp$Embedder(path = path, architecture = architecture)
 3. reticulate:::py_call_impl(callable, dots$args, dots$keywords)

== testthat results  ===========================================================
[ OK: 12 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 15 ]
1. Failure: transformer_download_model() with default create all required model files in the package folder (@test-embed.R#5) 
2. Failure: transformer_download_model() with default create all required model files in the package folder (@test-embed.R#6) 
3. Failure: transformer_download_model() with default create all required model files in the package folder (@test-embed.R#7) 
4. Failure: transformer_download_model() with default create all required model files in the package folder (@test-embed.R#8) 
5. Failure: transformer_download_model() with default create all required model files in the package folder (@test-embed.R#9) 
6. Failure: second occurence of the same transformer_download_model() uses cached files (@test-embed.R#18) 
7. Error: DistilBERT model architecture can be download (@test-embed.R#32) 
8. Error: GTP model architecture can be loaded and is able to tokenize sentences (@test-embed.R#56) 
9. Error: GTP-2 model architecture can be loaded and is able to tokenize sentences (@test-embed.R#56) 
1. ...

Error: testthat unit tests failed
Execution halted

1 error x | 5 warnings x | 5 notes x
```

**Comment by jwijffels** [comment]
feel free to push your name in the DESCRIPTION file as author

**Pull request merged**
